name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.13.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.13.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          pytest test_main.py
      - name: Build Docker image
        run: docker build -t mlops-assignment .

      - name: Logging in to Docker Hub
        run: docker login -u ramsaba0246 -p @Dream12345

      - name: Pushing Docker image
        run: docker push mlops-api:latest